name: Upload latest image to Registry

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: "feed-digest"

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: lowercase github.repository_owner
        run: |
          echo "OWNER=`echo ${{github.repository_owner}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push latest Docker image with BuildKit cache
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.OWNER }}/${{ env.IMAGE_NAME }}:latest
          cache-from: |
            type=registry,ref=ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:buildcache
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=ghcr.io/${{ env.OWNER }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
            type=local,dest=/tmp/.buildx-cache,mode=max
        env:
          DOCKER_BUILDKIT: 1
